# Generated by Django 4.0.6 on 2024-04-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image1', models.ImageField(upload_to='cours/%y/%m/%d')),
                ('image2', models.ImageField(upload_to='cours/%y/%m/%d')),
                ('file', models.FileField(upload_to='')),
                ('category', models.CharField(max_length=100)),
                ('classe', models.CharField(max_length=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image1', models.ImageField(upload_to='exercices/%y/%m/%d')),
                ('image2', models.ImageField(upload_to='exercices/%y/%m/%d')),
                ('file', models.FileField(upload_to='')),
                ('category', models.CharField(max_length=100)),
                ('classe', models.CharField(max_length=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image1', models.ImageField(upload_to='exercices/%y/%m/%d')),
                ('image2', models.ImageField(upload_to='exercices/%y/%m/%d')),
                ('file', models.FileField(upload_to='')),
                ('category', models.CharField(max_length=100)),
                ('classe', models.CharField(max_length=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image1', models.ImageField(upload_to='exercices/%y/%m/%d')),
                ('image2', models.ImageField(upload_to='exercices/%y/%m/%d')),
                ('file', models.FileField(upload_to='')),
                ('category', models.CharField(max_length=100)),
                ('classe', models.CharField(max_length=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Probleme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image1', models.ImageField(upload_to='exercices/%y/%m/%d')),
                ('image2', models.ImageField(upload_to='exercices/%y/%m/%d')),
                ('file', models.FileField(upload_to='')),
                ('category', models.CharField(max_length=100)),
                ('classe', models.CharField(max_length=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
