# Generated by Django 4.0.6 on 2024-04-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_cours_dl_ds_exercice_probleme_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='matiere',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='dl',
            name='matiere',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='ds',
            name='matiere',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='exercice',
            name='matiere',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='probleme',
            name='matiere',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
