# Generated by Django 4.0.6 on 2024-04-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_cours_matiere_dl_matiere_ds_matiere_exercice_matiere_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='file',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
