# Generated by Django 4.0.6 on 2024-04-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_cours_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dl',
            name='file',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='dl',
            name='image1',
            field=models.ImageField(upload_to='cours/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='dl',
            name='image2',
            field=models.ImageField(upload_to='cours/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='ds',
            name='file',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='ds',
            name='image1',
            field=models.ImageField(upload_to='cours/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='ds',
            name='image2',
            field=models.ImageField(upload_to='cours/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='exercice',
            name='file',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='exercice',
            name='image1',
            field=models.ImageField(upload_to='cours/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='exercice',
            name='image2',
            field=models.ImageField(upload_to='cours/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='probleme',
            name='file',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='probleme',
            name='image1',
            field=models.ImageField(upload_to='cours/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='probleme',
            name='image2',
            field=models.ImageField(upload_to='cours/%y/%m/%d'),
        ),
    ]
