# Generated by Django 4.0.6 on 2024-04-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_dl_file_alter_dl_image1_alter_dl_image2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('classe', models.CharField(max_length=100)),
                ('image1', models.ImageField(upload_to='users/%y/%m/%d')),
            ],
        ),
        migrations.AlterField(
            model_name='dl',
            name='image1',
            field=models.ImageField(upload_to='dl/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='dl',
            name='image2',
            field=models.ImageField(upload_to='dl/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='ds',
            name='image1',
            field=models.ImageField(upload_to='ds/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='ds',
            name='image2',
            field=models.ImageField(upload_to='ds/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='exercice',
            name='image1',
            field=models.ImageField(upload_to='exos/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='exercice',
            name='image2',
            field=models.ImageField(upload_to='exos/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='probleme',
            name='image1',
            field=models.ImageField(upload_to='prob/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='probleme',
            name='image2',
            field=models.ImageField(upload_to='prob/%y/%m/%d'),
        ),
    ]
