# Generated by Django 4.0.6 on 2024-04-05 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_user_alter_dl_image1_alter_dl_image2_alter_ds_image1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Eleve',
        ),
    ]
