# Generated by Django 4.0.6 on 2024-04-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_eleve_delete_eleves'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('classe', models.CharField(max_length=100)),
                ('image1', models.ImageField(upload_to='users/%y/%m/%d')),
            ],
        ),
    ]
