# Generated by Django 4.0.6 on 2024-04-06 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_delete_tops'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eleve',
        ),
    ]
