# Generated by Django 4.0.6 on 2024-04-06 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_eleve'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eleve',
        ),
    ]
