# Generated by Django 5.0.4 on 2024-04-09 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_eleve'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='telephone',
            field=models.CharField(default='0600000000', max_length=100),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='image1',
            field=models.ImageField(default='/Users/mac/Desktop/lem6students/lem6students/static/default.png', upload_to='users/%y/%m/%d'),
        ),
    ]
