# Generated by Django 5.0.4 on 2024-04-09 03:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_eleve_telephone_alter_eleve_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='anniv',
            field=models.DateField(default=datetime.date(2024, 1, 1)),
        ),
    ]
