# Generated by Django 5.0.4 on 2024-04-10 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_alter_eleve_image1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DS',
            new_name='CNC',
        ),
        migrations.DeleteModel(
            name='DL',
        ),
        migrations.AlterField(
            model_name='eleve',
            name='image1',
            field=models.ImageField(upload_to='users/%y/%m/%d'),
        ),
    ]
